FROM {{BASE_IMG}}

ARG SPACK_VERSION

RUN apk --no-cache add \
      build-base wget tar python2 curl bash procps \
      gfortran patch perl linux-headers xz git \
 && wget --no-check-certificate -O - https://github.com/LLNL/spack/archive/${SPACK_VERSION}.tar.gz | tar xz \
 && mv /spack-* /spack \
 && rm -rf /var/cache/apk/* \
 && bash -c "source /spack/share/spack/setup-env.sh && spack bootstrap"

ENV SPACK_ROOT=/spack
ENV PATH=/usr/local/bin/patch:$PATH:/spack/bin

ENTRYPOINT ["spack"]
