FROM {{BASE_IMG}}

ARG SPACK_VERSION

RUN apt-get update \
 && apt-get install -y build-essential wget tar python-minimal curl gfortran unzip \
 && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
 && wget --no-check-certificate -O - https://github.com/LLNL/spack/archive/${SPACK_VERSION}.tar.gz | tar xz \
 && mv /spack-* /spack

ENV SPACK_ROOT=/spack
ENV PATH=$PATH:/spack/bin

COPY spackload /usr/bin/

RUN spack bootstrap

ENTRYPOINT ["spack"]
